In [15]:
import tensorflow as tf

In [16]:
daily_sales = [21,22,-108,31,-1,32,34,31]

In [17]:
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales)

In [18]:
tf_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [19]:
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
22
-108
31
-1
32
34
31


In [20]:
for sales in tf_dataset.take(3):
    print(sales.numpy())

21
22
-108


In [21]:
tf_dataset = tf_dataset.filter(lambda x:x>0)
for sales in tf_dataset:
    print(sales.numpy())

21
22
31
32
34
31


In [22]:
tf_dataset = tf_dataset.map(lambda x:x*72)
tf_dataset = tf_dataset.shuffle(3)
for sales in tf_dataset:
    print(sales.numpy())

2232
1584
2304
2232
2448
1512


In [23]:
for sales_batch in tf_dataset.batch(4):
    print(sales_batch.numpy())

[1584 2304 2448 2232]
[2232 1512]


In [57]:
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales)

tf_dataset = tf_dataset.filter(lambda x:x>0).map(lambda y:y*72).shuffle(2).batch(2)

In [58]:
for sales in tf_dataset:
    print(sales.numpy())

[1512 2232]
[1584 2304]
[2232 2448]


In [59]:
images_ds = tf.data.Dataset.list_files('images/*/*', shuffle = False)

for file in images_ds.take(5):
    print(file.numpy())

b'images\\cat\\20 Reasons Why Cats Make the Best Pets....jpg'
b'images\\cat\\7 Foods Your Cat Can_t Eat.jpg'
b'images\\cat\\A cat appears to have caught the....jpg'
b'images\\cat\\Adopt-A-Cat Month\xc2\xae - American Humane....jpg'
b'images\\cat\\All About Your Cat_s Tongue.jpg'


In [60]:
images_ds = images_ds.shuffle(200)

for file in images_ds.take(5):
    print(file.numpy())

b'images\\cat\\Orlando Cat Caf\xc3\xa9.png'
b'images\\dog\\Science_ Talking to Your Dog Means You....jpg'
b'images\\cat\\Why Cats Sniff Rear Ends _ VCA Animal....png'
b'images\\cat\\Pet Insurance for Cats & Kittens _ Petplan.png'
b'images\\dog\\How Many Dog Breeds Are There_ _ Hill_s Pet.jpg'


In [61]:
class_name = ["cat", "dog"]

In [62]:
image_count = len(images_ds)
image_count

130

In [63]:
train_size = int(image_count*0.8)

train_ds = images_ds.take(train_size)
test_ds = images_ds.skip(train_size)

In [64]:
len(train_ds)

104

In [65]:
len(test_ds)

26

In [66]:
s = 'images\\cat\\The Science-Backed Benefits of Being a....jpg'
s.split("\\")[1]

'cat'

In [67]:
def get_label(file_path):
    import os
    return tf.strings.split(file_path, os.path.sep)[1]

In [68]:
def process_image(file_path):
    label = get_label(file_path)
    img = tf.io.read_file(file_path)
    img = tf.image.decode_jpeg(img)
    img = tf.image.resize(img, [128,128])

    return img,label

In [69]:
train_ds = train_ds.map(process_image)
for image,label in train_ds.take(3):
    print(f"Image : {image}")
    print(f"Label : {label}")

Image : [[[254.      254.      254.     ]
  [254.      254.      254.     ]
  [254.      254.      254.     ]
  ...
  [254.      254.      254.     ]
  [254.      254.      254.     ]
  [254.      254.      254.     ]]

 [[254.      254.      254.     ]
  [254.      254.      254.     ]
  [254.      254.      254.     ]
  ...
  [254.      254.      254.     ]
  [254.      254.      254.     ]
  [254.      254.      254.     ]]

 [[254.      254.      254.     ]
  [254.      254.      254.     ]
  [254.      254.      254.     ]
  ...
  [254.      254.      254.     ]
  [254.      254.      254.     ]
  [254.      254.      254.     ]]

 ...

 [[254.      254.      254.     ]
  [254.      254.      254.     ]
  [254.      254.      254.     ]
  ...
  [252.      252.      252.     ]
  [252.92188 252.92188 252.92188]
  [252.74902 252.74902 252.74902]]

 [[254.      254.      254.     ]
  [254.      254.      254.     ]
  [254.      254.      254.     ]
  ...
  [254.      254.      254.   

In [51]:
def scale(image, label):
    return image/255, label

In [70]:
train_ds = train_ds.map(scale)
for image,label in train_ds.take(5):
    print(f"**Image : {image.numpy()[0][0]}")
    print(f"**Label : {label.numpy()}")

**Image : [0.8432598  0.8079657  0.74129903]
**Label : b'dog'
**Image : [0.5887083  0.6632181  0.41223767]
**Label : b'dog'
**Image : [0.0891391  0.07345282 0.0381587 ]
**Label : b'dog'
**Image : [0.5981036 0.6666329 0.6666329]
**Label : b'cat'
**Image : [0.68235296 0.6784314  0.6627451 ]
**Label : b'cat'
