In [1]:
import numpy as np

In [2]:
revenue = np.array([2,3,1])
expenses = np.array([[10,1,1],[20,2,0],[0,3,0]])
res = np.dot(revenue,expenses)
res

array([80, 11,  2])

In [3]:
y = [i for i in res]
y

[80, 11, 2]

In [6]:
revenue = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
rupees = 75
res = revenue * rupees
res

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [7]:
prices = np.array([20,30,15])
sold = np.array([[50,60,25],[10,13,5],[40,70,52]])
sale = np.dot(prices,sold)
sale

array([1900, 2640, 1430])